---
- name: Create new users
  hosts: node2.example.com
  vars_files:
    - ./loopvars.yml

  tasks:

  - name: Create Users
    user:
      name: "{{ item.key }}"
      comment: '{{ item.key }}@example.com'
      home: '/home/{{ item.key }}_homedir'
      password: "{{item.value | password_hash('sha512')}}"
      update_password: on_create
    loop: "{{ new_users | dict2items }}"

        
